codecov:
  disable_search: true
  notify:
    require_ci_to_pass: yes
coverage:
  status:
    project:
      default:
        target: auto
  parsers:
    gcov:
      enable: no
    pycoverage:
      enable: no
