# flag_management:
#   default_rules: # the rules that will be followed for any flag added, generally
#     carryforward: true
# flag_management:
#   default_rules: # the rules that will be followed for any flag added, generally
#     carryforward: true

component_management:
  default_rules: # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: test-codecov # this is an identifier that should not be changed
      name: codecov-component # this is a display name, and can be changed freely
      paths:
        - src/test-codecov/**
